[build]
publish = "site"
command = """
pip3 install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry install -v &&
printf "\n\n\n" &&
pip3 freeze &&
printf "\n\n\n" &&
mkdocs build -d site
"""