[build]
publish = "site"
command = """
pip3 install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry install -v &&
pip3 install typing-extensions &&
pip3 freeze &&
mkdocs build -d site
"""